spring:
  thymeleaf:
    cache: false

  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/eazyschool
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true