# Disable caching
spring:
  thymeleaf:
    cache: false

  # Enable automatic restart
  devtools:
    restart:
      enabled: true

  # Database config
  datasource:
    # DATABASE connection
    url: jdbc:mysql://localhost:3306/eazyschool
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Base path for HAL explorer
  data:
    rest:
      basePath: /dr

  jpa:
    # Show sql queries made by spring data jpa
    show-sql: false
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: true

  # Show logs in colored mode
  output:
    ansi:
      enabled: ALWAYS

# Logging
# Set the severity to determine which logs are printed
logging:
  group:
    eazyschool_error: com.acme.eazyschool.aspects, com.acme.eazyschool.controller
  level:
    #    com:
    #      acme:
    #        eazyschool:
    #          aspects: ERROR
    #          controller: TRACE
    eazyschool_error: ERROR

# Custom properties
eazyschool:
  pageSize: 5
  contact:
    pageSize: 5
    successMessage: Your message is saved successfully
  branches: NewYork, Delhi, Paris, 