# Load this file upon activation of profile
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: INFO

# Custom properties
eazyschool:
  pageSize: 13
