spring:
  application:
  name: Melbourne band

  config:
    import: application_prod.yaml
  profiles:
    active: prod

  # Security config
  security:
    user:
      name: user
      password: admin

  # Database config
  datasource:
    # DATABASE connection
    url: jdbc:mysql://localhost:3306/melbourneband
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # Show sql queries made by spring data jpa
    show-sql: false
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: true

  # Show logs in colored mode
  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8086